# Generated by Django 5.0.4 on 2024-04-30 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Xomashyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('remainder', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=True)),
                ('xomashyo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xomashyo_store', to='products.xomashyo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='XomashyoMahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('mahsulot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahsulot', to='products.mahsulot')),
                ('xomashyo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xomashyo', to='products.xomashyo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
