# Generated by Django 5.0.4 on 2024-05-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_mahsulot_kodi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xomashyomahsulot',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
