# Generated by Django 5.0.4 on 2024-05-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_store_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='price',
            field=models.FloatField(),
        ),
    ]
